### ISSUE TITLE
Error while Installing

### ISSUE THREAD

**Issue by dustinjoe** [Xilinx/PYNQ-DL#2]
Hello. I encountered an error when installing using the command:

llecting git+https://github.com/Xilinx/PYNQ-DL.git
  Cloning https://github.com/Xilinx/PYNQ-DL.git to /tmp/pip-req-build-tnq2hrn9
Installing collected packages: pynqDL
  Running setup.py install for pynqDL ... error
    Complete output from command /opt/python3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-tnq2hrn9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ucjpjnm0/install-record.txt --single-version-externally-managed --compile:
    Reading package lists...
    Building dependency tree...
    Reading state information...
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    ERROR: You must give at least one requirement to install (see "pip help install")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-tnq2hrn9/setup.py", line 106, in <module>
        install_packages()
      File "/tmp/pip-req-build-tnq2hrn9/setup.py", line 48, in install_packages
        subprocess.check_call(['pip3.6', 'install'])
      File "/opt/python3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pip3.6', 'install']' returned non-zero exit status 1.

    ----------------------------------------
Command "/opt/python3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-tnq2hrn9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ucjpjnm0/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-tnq2hrn9/

**Comment by npurusho** [comment]
Hi,
 
The following command should work on the latest PYNQ image v2.2
http://pynq-testing.readthedocs.io/en/image_v2.2/getting_started/pynq_image.html

` sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-DL.git`

what changes have you made to the basic pynq image?
Can you try with a new sd card and clean image of pynq?

**Comment by dustinjoe** [comment]
Hi, Naveen :
       Thanks for your comment. So does this work only on 2.2? 
       I am using a Digilent Z1 board which seems to be 2.1 highest according to the link.

**Comment by npurusho** [comment]
Hi,


v2.1 should be fine.
Can you try on a new SD image?

**Comment by yunqu** [comment]
If you want to work with 2.2, just try pip install upgrade your pynq package.

**Comment by dustinjoe** [comment]
Thank you for your suggestions. Actually I am using a 32g SanDisk tf card now. I will first try to use another microsd card. 
By the way, if I want to implement LSTM on PYNQ, is there any suggested solutions? Thanks again!

**Comment by npurusho** [comment]
Here is a link that maybe useful:
https://github.com/tukl-msd/LSTM-PYNQ

you can find some other PYNQ projects here:
http://www.pynq.io/community.html

**Comment by dustinjoe** [comment]
Hi:
    I have just changed a card and successfully installed this package. The difference I can think of that may be the cause this problem is:

u are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' 

I upgraded that for the previous card but not for this card. The old pip version works. There might be some compatible differences for these two pip versions. Thank you!
