### ISSUE TITLE
Installing on PYNQ 2.3

### ISSUE THREAD

**Issue by Sayf-Khan** [Xilinx/PYNQ-DL#3]
Hello,

I have tried installing this with the following (as stated in the instructions):
sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-DL.git

however, this gave the following error
pip3.6: command not found

I believe the new command is pip3 (since this change worked with another git repo), so I changed it to the following:
sudo -H pip3 install --upgrade git+https://github.com/Xilinx/PYNQ-DL.git

This showed the installation was successful and following this, I had rebooted, however, no new notebooks appeared, any advice would but much appreciated.

**Comment by binemugha** [comment]
I had the same problem with the pip3.6 but I upgraded my pip from 3 to 3.6. But however, I used the reboot command but nothing happened and no new Jupyter notebook was added and I did not even see the folder (PYNQ-DL)
